version: "3.8"
services:
  ## TODO: Configure chainlink
  ## TODO: Configure postgresql
  chainlink-sepolia-node:
    image: smartcontract/chainlink:2.6.0
    container_name: chainlink-sepolia-node
    volumes:
      - .chainlink-sepolia/config.toml:/chainlink/config.toml
      - ~/.chainlink/sepolia/secrets/secrets.toml:/chainlink/secrets.toml
      - ~/.chainlink/sepolia/secrets/api.txt:/chainlink/.api
    ports:
      - 6688:6688
    command:
      - -config /chainlink/config.json
      - --add-host=host.docker.internal:host-gateway
      - -secrets /chainlink/secrets.toml
      - start
      - -a /chainlink/.api
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ulimits:
      nofile:
        soft: 20000
        hard: 20000

  chainlink-sepolia-postgres:
    image: postgres:16.0
    container_name: chainlink-sepolia-postgres
    volumes:
      - ~/.chainlink/sepolia/postgres:/var/lib/postgresql/data
      - ~/.chainlink/sepolia/secrets/postgres_password.txt:/run/secrets/postgres-passwd
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: NotTellingYou
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    stop_grace_period: 500s
    stop_signal: SIGINT
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
