name                = "Get UK Carbon Intensity Index"
type                = "directrequest"
schemaVersion       = 1
evmChainID          = 11155111
contractAddress     = "0xd3e4028bC6b50091112641b565bE049f535D6299" # operator address
minIncomingConfirmations = 0

observationSource   = """
    decode_log      [type="ethabidecodelog"
                        abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                        data="$(jobRun.logData)"
                        topics="$(jobRun.logTopics)"]

    ds_fetch        [type="http" method=GET url="https://api.carbonintensity.org.uk/intensity"];
    ds_parse        [type="jsonparse" path="data,0,intensity,index"];

    encode_data     [type="ethabiencode" abi="(bytes32 requestId, string value)" data="{ \\"requestId\\": $(decode_log.requestId), \\"value\\": $(ds_parse) }"]
    encode_tx       [type="ethabiencode"
                        abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                        data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\":   $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"]
    submit_tx       [type="ethtx" to="0xd3e4028bC6b50091112641b565bE049f535D6299" data="$(encode_tx)"]

    decode_log -> ds_fetch -> ds_parse -> encode_data -> encode_tx -> submit_tx;

"""